name: deos
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ^2.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  provider: ^6.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  device_frame: 0.4.2
  another_flushbar: ^1.10.28
  flutter_staggered_grid_view: 0.4.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
